language: c
os:
  - linux
  - osx
compiler:
  - gcc
  - clang
env:
  - PKGSRC_VERSION=2015Q3
  - PKGSRC_VERSION=2015Q4
  - PKGSRC_VERSION=2016Q1
  - PKGSRC_VERSION=2016Q2
  - PKGSRC_VERSION=2016Q4
script:
  - export SH=/bin/bash
  - curl -O https://s3.amazonaws.com/minipkg.eliteraspberries.com/pkgsrc-${PKGSRC_VERSION}.tar.gz
  - mkdir -p usr
  - gunzip < pkgsrc-${PKGSRC_VERSION}.tar.gz | tar -f - -x -C usr
  - cd usr/pkgsrc
  - >
    ./bootstrap/bootstrap
    --abi 64
    --compiler $CC
    --mk-fragment ../../mk.conf
    --unprivileged
    --prefer-pkgsrc no
after_success:
  - export PATH="$HOME/pkg/sbin:$PATH"
  - pkg_info
after_failure:
  - cat work/wrk/devel/bmake/work/libnbcompat/config.log
