language: c
os:
  - linux
  - osx
osx_image: xcode8
compiler:
  - gcc
  - clang
env:
  - PKGSRC_VERSION=2015Q4
  - PKGSRC_VERSION=2016Q4
  - PKGSRC_VERSION=2017Q4
  - PKGSRC_VERSION=2018Q1
  - PKGSRC_VERSION=2018Q2
script:
  - export GITHUB=https://github.com/eliteraspberries/pkgsrc-test
  - export SH=/bin/bash
  - >
    if test "${CC}" = "gcc"; then for version in 6 5 4.9 4.8; do
        gcc-${version} --version;
        if test "$?" = "0"; then
            export CC="gcc-${version}" CXX="g++-${version}";
            break;
        fi;
    done; fi
  - curl -L -O ${GITHUB}/releases/download/0.1/pkgsrc-${PKGSRC_VERSION}.tar.gz
  - mkdir -p usr
  - gunzip < pkgsrc-${PKGSRC_VERSION}.tar.gz | tar -f - -x -C usr
  - cd usr/pkgsrc
  - >
    for patch in patch-bsd.prefs.mk patch-bsd.sys.mk patch-compiler.mk; do
        curl -L -O ${GITHUB}/releases/download/0.1/$patch;
        patch -p0 < $patch || true;
    done
  - >
    ./bootstrap/bootstrap
    --abi 64
    --compiler $CC
    --mk-fragment ../../mk.conf
    --unprivileged
    --prefer-pkgsrc no
after_success:
  - export PATH="$HOME/pkg/sbin:$PATH"
  - pkg_info
