language: c
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
      compiler: clang
    - os: osx
      compiler: clang
script:
  - curl -O http://cdn.netbsd.org/pub/pkgsrc/stable/pkgsrc.tar.bz2
  - mkdir -p usr
  - bunzip2 < pkgsrc.tar.bz2 | tar -f - -x -C usr
  - cd usr/pkgsrc
  - ./bootstrap/bootstrap --abi 64 --compiler clang --mk-fragment $HOME/eliteraspberries/pkgsrc-test/mk.conf --unprivileged
after_success:
  - export PATH="$HOME/pkg/sbin:$PATH"
  - pkg_info
